all: build run
build:
	#-m32 compile 32bit program, -g debugging, -o output
	gcc main.c -m32 -g -o demo_pretvori
run:
	#run built program
	./demo_pretvori 221A
clean:
	#-f force remove
	rm -f demo_pretvori